package practice;// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class IDEtest {
     WebDriver wd;

    @BeforeMethod
    public void setUp() {
        wd = new ChromeDriver();

    }

    @AfterMethod
    public void tearDown() {
        wd.quit();
    }

    @Test
    public void test() {
        wd.get("https://www.saucedemo.com/");
        wd.manage().window().maximize();
        wd.findElement(By.id("login_credentials")).click();
        wd.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
        wd.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
        wd.findElement(By.cssSelector(".login_password")).click();
        wd.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
        wd.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
        wd.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    }
}
